// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cinch/v1/auth.proto

package cinchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Hostname *string                `protobuf:"bytes,1,opt,name=hostname,proto3,oneof" json:"hostname,omitempty"`
	// Single-use invite token required when the relay has no OAuth provider
	// configured. Ignored on OAuth-enabled relays (they reject /auth/login
	// entirely). Format: "cinch_inv_<base32>".
	InviteCode *string `protobuf:"bytes,2,opt,name=invite_code,json=inviteCode,proto3,oneof" json:"invite_code,omitempty"`
	// Friendly display name the user types at the browser sign-in page.
	// Stored on `users.display_name`; shown in `relay user list`.
	DisplayName   *string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_cinch_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_cinch_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetHostname() string {
	if x != nil && x.Hostname != nil {
		return *x.Hostname
	}
	return ""
}

func (x *LoginRequest) GetInviteCode() string {
	if x != nil && x.InviteCode != nil {
		return *x.InviteCode
	}
	return ""
}

func (x *LoginRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_cinch_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_cinch_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type DeviceCodeStartRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Hostname *string                `protobuf:"bytes,1,opt,name=hostname,proto3,oneof" json:"hostname,omitempty"`
	// Stable per-machine identifier (opaque hash). When set, the relay reuses
	// an existing device row for the same (user_id, machine_id) instead of
	// creating a duplicate when the same Mac signs in via CLI and desktop.
	MachineId *string `protobuf:"bytes,2,opt,name=machine_id,json=machineId,proto3,oneof" json:"machine_id,omitempty"`
	// Email or user_id — relay broadcasts device_code_pending to this user's
	// WS sessions so already-signed-in devices can approve/deny.
	UserHint      *string `protobuf:"bytes,3,opt,name=user_hint,json=userHint,proto3,oneof" json:"user_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceCodeStartRequest) Reset() {
	*x = DeviceCodeStartRequest{}
	mi := &file_cinch_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCodeStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCodeStartRequest) ProtoMessage() {}

func (x *DeviceCodeStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCodeStartRequest.ProtoReflect.Descriptor instead.
func (*DeviceCodeStartRequest) Descriptor() ([]byte, []int) {
	return file_cinch_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceCodeStartRequest) GetHostname() string {
	if x != nil && x.Hostname != nil {
		return *x.Hostname
	}
	return ""
}

func (x *DeviceCodeStartRequest) GetMachineId() string {
	if x != nil && x.MachineId != nil {
		return *x.MachineId
	}
	return ""
}

func (x *DeviceCodeStartRequest) GetUserHint() string {
	if x != nil && x.UserHint != nil {
		return *x.UserHint
	}
	return ""
}

type DeviceCodeStartResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeviceCode      string                 `protobuf:"bytes,1,opt,name=device_code,json=deviceCode,proto3" json:"device_code,omitempty"`
	UserCode        string                 `protobuf:"bytes,2,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`
	VerificationUri string                 `protobuf:"bytes,3,opt,name=verification_uri,json=verificationUri,proto3" json:"verification_uri,omitempty"`
	ExpiresIn       int64                  `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	Interval        int64                  `protobuf:"varint,5,opt,name=interval,proto3" json:"interval,omitempty"`
	// Suggested polling interval in milliseconds. When non-zero, clients use
	// this in place of `interval` (seconds) for tighter UX. Older clients
	// ignore the field and fall back to `interval`.
	IntervalMs    *int64 `protobuf:"varint,6,opt,name=interval_ms,json=intervalMs,proto3,oneof" json:"interval_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceCodeStartResponse) Reset() {
	*x = DeviceCodeStartResponse{}
	mi := &file_cinch_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCodeStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCodeStartResponse) ProtoMessage() {}

func (x *DeviceCodeStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCodeStartResponse.ProtoReflect.Descriptor instead.
func (*DeviceCodeStartResponse) Descriptor() ([]byte, []int) {
	return file_cinch_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceCodeStartResponse) GetDeviceCode() string {
	if x != nil {
		return x.DeviceCode
	}
	return ""
}

func (x *DeviceCodeStartResponse) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

func (x *DeviceCodeStartResponse) GetVerificationUri() string {
	if x != nil {
		return x.VerificationUri
	}
	return ""
}

func (x *DeviceCodeStartResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *DeviceCodeStartResponse) GetInterval() int64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *DeviceCodeStartResponse) GetIntervalMs() int64 {
	if x != nil && x.IntervalMs != nil {
		return *x.IntervalMs
	}
	return 0
}

type DeviceCodePollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceCodePollRequest) Reset() {
	*x = DeviceCodePollRequest{}
	mi := &file_cinch_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCodePollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCodePollRequest) ProtoMessage() {}

func (x *DeviceCodePollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCodePollRequest.ProtoReflect.Descriptor instead.
func (*DeviceCodePollRequest) Descriptor() ([]byte, []int) {
	return file_cinch_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceCodePollRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type DeviceCodePollResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Token            *string                `protobuf:"bytes,2,opt,name=token,proto3,oneof" json:"token,omitempty"`
	UserId           *string                `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	DeviceId         *string                `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3,oneof" json:"device_id,omitempty"`
	Email            *string                `protobuf:"bytes,5,opt,name=email,proto3,oneof" json:"email,omitempty"`
	IdentityProvider *string                `protobuf:"bytes,6,opt,name=identity_provider,json=identityProvider,proto3,oneof" json:"identity_provider,omitempty"`
	// Effective display name — `users.display_name` if the user has set one,
	// otherwise the OAuth-fetched name (GitHub `name`/`login`, Google `name`).
	// Empty when no name is available.
	DisplayName   *string `protobuf:"bytes,7,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceCodePollResponse) Reset() {
	*x = DeviceCodePollResponse{}
	mi := &file_cinch_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCodePollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCodePollResponse) ProtoMessage() {}

func (x *DeviceCodePollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCodePollResponse.ProtoReflect.Descriptor instead.
func (*DeviceCodePollResponse) Descriptor() ([]byte, []int) {
	return file_cinch_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceCodePollResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeviceCodePollResponse) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *DeviceCodePollResponse) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *DeviceCodePollResponse) GetDeviceId() string {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return ""
}

func (x *DeviceCodePollResponse) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *DeviceCodePollResponse) GetIdentityProvider() string {
	if x != nil && x.IdentityProvider != nil {
		return *x.IdentityProvider
	}
	return ""
}

func (x *DeviceCodePollResponse) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

type DeviceCodeCompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserCode      string                 `protobuf:"bytes,1,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceCodeCompleteRequest) Reset() {
	*x = DeviceCodeCompleteRequest{}
	mi := &file_cinch_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCodeCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCodeCompleteRequest) ProtoMessage() {}

func (x *DeviceCodeCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCodeCompleteRequest.ProtoReflect.Descriptor instead.
func (*DeviceCodeCompleteRequest) Descriptor() ([]byte, []int) {
	return file_cinch_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceCodeCompleteRequest) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

func (x *DeviceCodeCompleteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeviceCodeCompleteRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceCodeCompleteRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type DeviceCodeCompleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceCodeCompleteResponse) Reset() {
	*x = DeviceCodeCompleteResponse{}
	mi := &file_cinch_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCodeCompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCodeCompleteResponse) ProtoMessage() {}

func (x *DeviceCodeCompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCodeCompleteResponse.ProtoReflect.Descriptor instead.
func (*DeviceCodeCompleteResponse) Descriptor() ([]byte, []int) {
	return file_cinch_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *DeviceCodeCompleteResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeviceCodeDenyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserCode      string                 `protobuf:"bytes,1,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceCodeDenyRequest) Reset() {
	*x = DeviceCodeDenyRequest{}
	mi := &file_cinch_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCodeDenyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCodeDenyRequest) ProtoMessage() {}

func (x *DeviceCodeDenyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCodeDenyRequest.ProtoReflect.Descriptor instead.
func (*DeviceCodeDenyRequest) Descriptor() ([]byte, []int) {
	return file_cinch_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *DeviceCodeDenyRequest) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

type DeviceCodeDenyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceCodeDenyResponse) Reset() {
	*x = DeviceCodeDenyResponse{}
	mi := &file_cinch_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCodeDenyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCodeDenyResponse) ProtoMessage() {}

func (x *DeviceCodeDenyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCodeDenyResponse.ProtoReflect.Descriptor instead.
func (*DeviceCodeDenyResponse) Descriptor() ([]byte, []int) {
	return file_cinch_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *DeviceCodeDenyResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type RevokeDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeDeviceRequest) Reset() {
	*x = RevokeDeviceRequest{}
	mi := &file_cinch_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeDeviceRequest) ProtoMessage() {}

func (x *RevokeDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeDeviceRequest.ProtoReflect.Descriptor instead.
func (*RevokeDeviceRequest) Descriptor() ([]byte, []int) {
	return file_cinch_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *RevokeDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type RevokeDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	RevokedAt     string                 `protobuf:"bytes,3,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeDeviceResponse) Reset() {
	*x = RevokeDeviceResponse{}
	mi := &file_cinch_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeDeviceResponse) ProtoMessage() {}

func (x *RevokeDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeDeviceResponse.ProtoReflect.Descriptor instead.
func (*RevokeDeviceResponse) Descriptor() ([]byte, []int) {
	return file_cinch_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *RevokeDeviceResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RevokeDeviceResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RevokeDeviceResponse) GetRevokedAt() string {
	if x != nil {
		return x.RevokedAt
	}
	return ""
}

type KeyBundlePutRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DeviceId           string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	EphemeralPublicKey string                 `protobuf:"bytes,2,opt,name=ephemeral_public_key,json=ephemeralPublicKey,proto3" json:"ephemeral_public_key,omitempty"`
	EncryptedBundle    string                 `protobuf:"bytes,3,opt,name=encrypted_bundle,json=encryptedBundle,proto3" json:"encrypted_bundle,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *KeyBundlePutRequest) Reset() {
	*x = KeyBundlePutRequest{}
	mi := &file_cinch_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyBundlePutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyBundlePutRequest) ProtoMessage() {}

func (x *KeyBundlePutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyBundlePutRequest.ProtoReflect.Descriptor instead.
func (*KeyBundlePutRequest) Descriptor() ([]byte, []int) {
	return file_cinch_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *KeyBundlePutRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *KeyBundlePutRequest) GetEphemeralPublicKey() string {
	if x != nil {
		return x.EphemeralPublicKey
	}
	return ""
}

func (x *KeyBundlePutRequest) GetEncryptedBundle() string {
	if x != nil {
		return x.EncryptedBundle
	}
	return ""
}

type KeyBundlePutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyBundlePutResponse) Reset() {
	*x = KeyBundlePutResponse{}
	mi := &file_cinch_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyBundlePutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyBundlePutResponse) ProtoMessage() {}

func (x *KeyBundlePutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyBundlePutResponse.ProtoReflect.Descriptor instead.
func (*KeyBundlePutResponse) Descriptor() ([]byte, []int) {
	return file_cinch_v1_auth_proto_rawDescGZIP(), []int{13}
}

func (x *KeyBundlePutResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type KeyBundleGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyBundleGetRequest) Reset() {
	*x = KeyBundleGetRequest{}
	mi := &file_cinch_v1_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyBundleGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyBundleGetRequest) ProtoMessage() {}

func (x *KeyBundleGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyBundleGetRequest.ProtoReflect.Descriptor instead.
func (*KeyBundleGetRequest) Descriptor() ([]byte, []int) {
	return file_cinch_v1_auth_proto_rawDescGZIP(), []int{14}
}

type KeyBundleGetResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EphemeralPublicKey string                 `protobuf:"bytes,1,opt,name=ephemeral_public_key,json=ephemeralPublicKey,proto3" json:"ephemeral_public_key,omitempty"`
	EncryptedBundle    string                 `protobuf:"bytes,2,opt,name=encrypted_bundle,json=encryptedBundle,proto3" json:"encrypted_bundle,omitempty"`
	// RFC3339 timestamp of when this device first registered its
	// public key. Empty if the bundle is already present.
	PendingSince  string `protobuf:"bytes,3,opt,name=pending_since,json=pendingSince,proto3" json:"pending_since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyBundleGetResponse) Reset() {
	*x = KeyBundleGetResponse{}
	mi := &file_cinch_v1_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyBundleGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyBundleGetResponse) ProtoMessage() {}

func (x *KeyBundleGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyBundleGetResponse.ProtoReflect.Descriptor instead.
func (*KeyBundleGetResponse) Descriptor() ([]byte, []int) {
	return file_cinch_v1_auth_proto_rawDescGZIP(), []int{15}
}

func (x *KeyBundleGetResponse) GetEphemeralPublicKey() string {
	if x != nil {
		return x.EphemeralPublicKey
	}
	return ""
}

func (x *KeyBundleGetResponse) GetEncryptedBundle() string {
	if x != nil {
		return x.EncryptedBundle
	}
	return ""
}

func (x *KeyBundleGetResponse) GetPendingSince() string {
	if x != nil {
		return x.PendingSince
	}
	return ""
}

type KeyBundleRetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyBundleRetryRequest) Reset() {
	*x = KeyBundleRetryRequest{}
	mi := &file_cinch_v1_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyBundleRetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyBundleRetryRequest) ProtoMessage() {}

func (x *KeyBundleRetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyBundleRetryRequest.ProtoReflect.Descriptor instead.
func (*KeyBundleRetryRequest) Descriptor() ([]byte, []int) {
	return file_cinch_v1_auth_proto_rawDescGZIP(), []int{16}
}

type KeyBundleRetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyBundleRetryResponse) Reset() {
	*x = KeyBundleRetryResponse{}
	mi := &file_cinch_v1_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyBundleRetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyBundleRetryResponse) ProtoMessage() {}

func (x *KeyBundleRetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyBundleRetryResponse.ProtoReflect.Descriptor instead.
func (*KeyBundleRetryResponse) Descriptor() ([]byte, []int) {
	return file_cinch_v1_auth_proto_rawDescGZIP(), []int{17}
}

func (x *KeyBundleRetryResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type RegisterDevicePublicKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // base64url X25519 pubkey
	Fingerprint   string                 `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`              // 8-hex-char SHA-256 prefix of raw pubkey bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDevicePublicKeyRequest) Reset() {
	*x = RegisterDevicePublicKeyRequest{}
	mi := &file_cinch_v1_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDevicePublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDevicePublicKeyRequest) ProtoMessage() {}

func (x *RegisterDevicePublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDevicePublicKeyRequest.ProtoReflect.Descriptor instead.
func (*RegisterDevicePublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_cinch_v1_auth_proto_rawDescGZIP(), []int{18}
}

func (x *RegisterDevicePublicKeyRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *RegisterDevicePublicKeyRequest) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

type RegisterDevicePublicKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDevicePublicKeyResponse) Reset() {
	*x = RegisterDevicePublicKeyResponse{}
	mi := &file_cinch_v1_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDevicePublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDevicePublicKeyResponse) ProtoMessage() {}

func (x *RegisterDevicePublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDevicePublicKeyResponse.ProtoReflect.Descriptor instead.
func (*RegisterDevicePublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_cinch_v1_auth_proto_rawDescGZIP(), []int{19}
}

func (x *RegisterDevicePublicKeyResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type SetDisplayNameRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New display name. Trimmed server-side; must be non-empty after trim.
	// Length cap: 64 bytes (UTF-8). Longer values return InvalidArgument.
	DisplayName   string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDisplayNameRequest) Reset() {
	*x = SetDisplayNameRequest{}
	mi := &file_cinch_v1_auth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDisplayNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDisplayNameRequest) ProtoMessage() {}

func (x *SetDisplayNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_auth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDisplayNameRequest.ProtoReflect.Descriptor instead.
func (*SetDisplayNameRequest) Descriptor() ([]byte, []int) {
	return file_cinch_v1_auth_proto_rawDescGZIP(), []int{20}
}

func (x *SetDisplayNameRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type SetDisplayNameResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// The stored value after trim/validation, so the caller can refresh its
	// local cache without a follow-up read.
	DisplayName   string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDisplayNameResponse) Reset() {
	*x = SetDisplayNameResponse{}
	mi := &file_cinch_v1_auth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDisplayNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDisplayNameResponse) ProtoMessage() {}

func (x *SetDisplayNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_auth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDisplayNameResponse.ProtoReflect.Descriptor instead.
func (*SetDisplayNameResponse) Descriptor() ([]byte, []int) {
	return file_cinch_v1_auth_proto_rawDescGZIP(), []int{21}
}

func (x *SetDisplayNameResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SetDisplayNameResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Fix           string                 `protobuf:"bytes,3,opt,name=fix,proto3" json:"fix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_cinch_v1_auth_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_auth_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_cinch_v1_auth_proto_rawDescGZIP(), []int{22}
}

func (x *ErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetFix() string {
	if x != nil {
		return x.Fix
	}
	return ""
}

var File_cinch_v1_auth_proto protoreflect.FileDescriptor

const file_cinch_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x13cinch/v1/auth.proto\x12\bcinch.v1\"\xab\x01\n" +
	"\fLoginRequest\x12\x1f\n" +
	"\bhostname\x18\x01 \x01(\tH\x00R\bhostname\x88\x01\x01\x12$\n" +
	"\vinvite_code\x18\x02 \x01(\tH\x01R\n" +
	"inviteCode\x88\x01\x01\x12&\n" +
	"\fdisplay_name\x18\x03 \x01(\tH\x02R\vdisplayName\x88\x01\x01B\v\n" +
	"\t_hostnameB\x0e\n" +
	"\f_invite_codeB\x0f\n" +
	"\r_display_name\"m\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceIdJ\x04\b\x02\x10\x03R\n" +
	"pair_token\"\xa9\x01\n" +
	"\x16DeviceCodeStartRequest\x12\x1f\n" +
	"\bhostname\x18\x01 \x01(\tH\x00R\bhostname\x88\x01\x01\x12\"\n" +
	"\n" +
	"machine_id\x18\x02 \x01(\tH\x01R\tmachineId\x88\x01\x01\x12 \n" +
	"\tuser_hint\x18\x03 \x01(\tH\x02R\buserHint\x88\x01\x01B\v\n" +
	"\t_hostnameB\r\n" +
	"\v_machine_idB\f\n" +
	"\n" +
	"_user_hint\"\xf3\x01\n" +
	"\x17DeviceCodeStartResponse\x12\x1f\n" +
	"\vdevice_code\x18\x01 \x01(\tR\n" +
	"deviceCode\x12\x1b\n" +
	"\tuser_code\x18\x02 \x01(\tR\buserCode\x12)\n" +
	"\x10verification_uri\x18\x03 \x01(\tR\x0fverificationUri\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x04 \x01(\x03R\texpiresIn\x12\x1a\n" +
	"\binterval\x18\x05 \x01(\x03R\binterval\x12$\n" +
	"\vinterval_ms\x18\x06 \x01(\x03H\x00R\n" +
	"intervalMs\x88\x01\x01B\x0e\n" +
	"\f_interval_ms\"+\n" +
	"\x15DeviceCodePollRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\xd5\x02\n" +
	"\x16DeviceCodePollResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x19\n" +
	"\x05token\x18\x02 \x01(\tH\x00R\x05token\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x03 \x01(\tH\x01R\x06userId\x88\x01\x01\x12 \n" +
	"\tdevice_id\x18\x04 \x01(\tH\x02R\bdeviceId\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x05 \x01(\tH\x03R\x05email\x88\x01\x01\x120\n" +
	"\x11identity_provider\x18\x06 \x01(\tH\x04R\x10identityProvider\x88\x01\x01\x12&\n" +
	"\fdisplay_name\x18\a \x01(\tH\x05R\vdisplayName\x88\x01\x01B\b\n" +
	"\x06_tokenB\n" +
	"\n" +
	"\b_user_idB\f\n" +
	"\n" +
	"_device_idB\b\n" +
	"\x06_emailB\x14\n" +
	"\x12_identity_providerB\x0f\n" +
	"\r_display_name\"\x84\x01\n" +
	"\x19DeviceCodeCompleteRequest\x12\x1b\n" +
	"\tuser_code\x18\x01 \x01(\tR\buserCode\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"4\n" +
	"\x1aDeviceCodeCompleteResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"4\n" +
	"\x15DeviceCodeDenyRequest\x12\x1b\n" +
	"\tuser_code\x18\x01 \x01(\tR\buserCode\"(\n" +
	"\x16DeviceCodeDenyResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"2\n" +
	"\x13RevokeDeviceRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"b\n" +
	"\x14RevokeDeviceResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"revoked_at\x18\x03 \x01(\tR\trevokedAt\"\x8f\x01\n" +
	"\x13KeyBundlePutRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x120\n" +
	"\x14ephemeral_public_key\x18\x02 \x01(\tR\x12ephemeralPublicKey\x12)\n" +
	"\x10encrypted_bundle\x18\x03 \x01(\tR\x0fencryptedBundle\"&\n" +
	"\x14KeyBundlePutResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x15\n" +
	"\x13KeyBundleGetRequest\"\x98\x01\n" +
	"\x14KeyBundleGetResponse\x120\n" +
	"\x14ephemeral_public_key\x18\x01 \x01(\tR\x12ephemeralPublicKey\x12)\n" +
	"\x10encrypted_bundle\x18\x02 \x01(\tR\x0fencryptedBundle\x12#\n" +
	"\rpending_since\x18\x03 \x01(\tR\fpendingSince\"\x17\n" +
	"\x15KeyBundleRetryRequest\"(\n" +
	"\x16KeyBundleRetryResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"a\n" +
	"\x1eRegisterDevicePublicKeyRequest\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\tR\vfingerprint\"1\n" +
	"\x1fRegisterDevicePublicKeyResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\":\n" +
	"\x15SetDisplayNameRequest\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\"K\n" +
	"\x16SetDisplayNameResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"Q\n" +
	"\rErrorResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x10\n" +
	"\x03fix\x18\x03 \x01(\tR\x03fix2\xb1\a\n" +
	"\vAuthService\x128\n" +
	"\x05Login\x12\x16.cinch.v1.LoginRequest\x1a\x17.cinch.v1.LoginResponse\x12V\n" +
	"\x0fDeviceCodeStart\x12 .cinch.v1.DeviceCodeStartRequest\x1a!.cinch.v1.DeviceCodeStartResponse\x12S\n" +
	"\x0eDeviceCodePoll\x12\x1f.cinch.v1.DeviceCodePollRequest\x1a .cinch.v1.DeviceCodePollResponse\x12_\n" +
	"\x12DeviceCodeComplete\x12#.cinch.v1.DeviceCodeCompleteRequest\x1a$.cinch.v1.DeviceCodeCompleteResponse\x12S\n" +
	"\x0eDeviceCodeDeny\x12\x1f.cinch.v1.DeviceCodeDenyRequest\x1a .cinch.v1.DeviceCodeDenyResponse\x12M\n" +
	"\fRevokeDevice\x12\x1d.cinch.v1.RevokeDeviceRequest\x1a\x1e.cinch.v1.RevokeDeviceResponse\x12M\n" +
	"\fKeyBundlePut\x12\x1d.cinch.v1.KeyBundlePutRequest\x1a\x1e.cinch.v1.KeyBundlePutResponse\x12M\n" +
	"\fKeyBundleGet\x12\x1d.cinch.v1.KeyBundleGetRequest\x1a\x1e.cinch.v1.KeyBundleGetResponse\x12S\n" +
	"\x0eKeyBundleRetry\x12\x1f.cinch.v1.KeyBundleRetryRequest\x1a .cinch.v1.KeyBundleRetryResponse\x12n\n" +
	"\x17RegisterDevicePublicKey\x12(.cinch.v1.RegisterDevicePublicKeyRequest\x1a).cinch.v1.RegisterDevicePublicKeyResponse\x12S\n" +
	"\x0eSetDisplayName\x12\x1f.cinch.v1.SetDisplayNameRequest\x1a .cinch.v1.SetDisplayNameResponseB4Z2github.com/cinchcli/relay/internal/cinchv1;cinchv1b\x06proto3"

var (
	file_cinch_v1_auth_proto_rawDescOnce sync.Once
	file_cinch_v1_auth_proto_rawDescData []byte
)

func file_cinch_v1_auth_proto_rawDescGZIP() []byte {
	file_cinch_v1_auth_proto_rawDescOnce.Do(func() {
		file_cinch_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cinch_v1_auth_proto_rawDesc), len(file_cinch_v1_auth_proto_rawDesc)))
	})
	return file_cinch_v1_auth_proto_rawDescData
}

var file_cinch_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_cinch_v1_auth_proto_goTypes = []any{
	(*LoginRequest)(nil),                    // 0: cinch.v1.LoginRequest
	(*LoginResponse)(nil),                   // 1: cinch.v1.LoginResponse
	(*DeviceCodeStartRequest)(nil),          // 2: cinch.v1.DeviceCodeStartRequest
	(*DeviceCodeStartResponse)(nil),         // 3: cinch.v1.DeviceCodeStartResponse
	(*DeviceCodePollRequest)(nil),           // 4: cinch.v1.DeviceCodePollRequest
	(*DeviceCodePollResponse)(nil),          // 5: cinch.v1.DeviceCodePollResponse
	(*DeviceCodeCompleteRequest)(nil),       // 6: cinch.v1.DeviceCodeCompleteRequest
	(*DeviceCodeCompleteResponse)(nil),      // 7: cinch.v1.DeviceCodeCompleteResponse
	(*DeviceCodeDenyRequest)(nil),           // 8: cinch.v1.DeviceCodeDenyRequest
	(*DeviceCodeDenyResponse)(nil),          // 9: cinch.v1.DeviceCodeDenyResponse
	(*RevokeDeviceRequest)(nil),             // 10: cinch.v1.RevokeDeviceRequest
	(*RevokeDeviceResponse)(nil),            // 11: cinch.v1.RevokeDeviceResponse
	(*KeyBundlePutRequest)(nil),             // 12: cinch.v1.KeyBundlePutRequest
	(*KeyBundlePutResponse)(nil),            // 13: cinch.v1.KeyBundlePutResponse
	(*KeyBundleGetRequest)(nil),             // 14: cinch.v1.KeyBundleGetRequest
	(*KeyBundleGetResponse)(nil),            // 15: cinch.v1.KeyBundleGetResponse
	(*KeyBundleRetryRequest)(nil),           // 16: cinch.v1.KeyBundleRetryRequest
	(*KeyBundleRetryResponse)(nil),          // 17: cinch.v1.KeyBundleRetryResponse
	(*RegisterDevicePublicKeyRequest)(nil),  // 18: cinch.v1.RegisterDevicePublicKeyRequest
	(*RegisterDevicePublicKeyResponse)(nil), // 19: cinch.v1.RegisterDevicePublicKeyResponse
	(*SetDisplayNameRequest)(nil),           // 20: cinch.v1.SetDisplayNameRequest
	(*SetDisplayNameResponse)(nil),          // 21: cinch.v1.SetDisplayNameResponse
	(*ErrorResponse)(nil),                   // 22: cinch.v1.ErrorResponse
}
var file_cinch_v1_auth_proto_depIdxs = []int32{
	0,  // 0: cinch.v1.AuthService.Login:input_type -> cinch.v1.LoginRequest
	2,  // 1: cinch.v1.AuthService.DeviceCodeStart:input_type -> cinch.v1.DeviceCodeStartRequest
	4,  // 2: cinch.v1.AuthService.DeviceCodePoll:input_type -> cinch.v1.DeviceCodePollRequest
	6,  // 3: cinch.v1.AuthService.DeviceCodeComplete:input_type -> cinch.v1.DeviceCodeCompleteRequest
	8,  // 4: cinch.v1.AuthService.DeviceCodeDeny:input_type -> cinch.v1.DeviceCodeDenyRequest
	10, // 5: cinch.v1.AuthService.RevokeDevice:input_type -> cinch.v1.RevokeDeviceRequest
	12, // 6: cinch.v1.AuthService.KeyBundlePut:input_type -> cinch.v1.KeyBundlePutRequest
	14, // 7: cinch.v1.AuthService.KeyBundleGet:input_type -> cinch.v1.KeyBundleGetRequest
	16, // 8: cinch.v1.AuthService.KeyBundleRetry:input_type -> cinch.v1.KeyBundleRetryRequest
	18, // 9: cinch.v1.AuthService.RegisterDevicePublicKey:input_type -> cinch.v1.RegisterDevicePublicKeyRequest
	20, // 10: cinch.v1.AuthService.SetDisplayName:input_type -> cinch.v1.SetDisplayNameRequest
	1,  // 11: cinch.v1.AuthService.Login:output_type -> cinch.v1.LoginResponse
	3,  // 12: cinch.v1.AuthService.DeviceCodeStart:output_type -> cinch.v1.DeviceCodeStartResponse
	5,  // 13: cinch.v1.AuthService.DeviceCodePoll:output_type -> cinch.v1.DeviceCodePollResponse
	7,  // 14: cinch.v1.AuthService.DeviceCodeComplete:output_type -> cinch.v1.DeviceCodeCompleteResponse
	9,  // 15: cinch.v1.AuthService.DeviceCodeDeny:output_type -> cinch.v1.DeviceCodeDenyResponse
	11, // 16: cinch.v1.AuthService.RevokeDevice:output_type -> cinch.v1.RevokeDeviceResponse
	13, // 17: cinch.v1.AuthService.KeyBundlePut:output_type -> cinch.v1.KeyBundlePutResponse
	15, // 18: cinch.v1.AuthService.KeyBundleGet:output_type -> cinch.v1.KeyBundleGetResponse
	17, // 19: cinch.v1.AuthService.KeyBundleRetry:output_type -> cinch.v1.KeyBundleRetryResponse
	19, // 20: cinch.v1.AuthService.RegisterDevicePublicKey:output_type -> cinch.v1.RegisterDevicePublicKeyResponse
	21, // 21: cinch.v1.AuthService.SetDisplayName:output_type -> cinch.v1.SetDisplayNameResponse
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_cinch_v1_auth_proto_init() }
func file_cinch_v1_auth_proto_init() {
	if File_cinch_v1_auth_proto != nil {
		return
	}
	file_cinch_v1_auth_proto_msgTypes[0].OneofWrappers = []any{}
	file_cinch_v1_auth_proto_msgTypes[2].OneofWrappers = []any{}
	file_cinch_v1_auth_proto_msgTypes[3].OneofWrappers = []any{}
	file_cinch_v1_auth_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cinch_v1_auth_proto_rawDesc), len(file_cinch_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cinch_v1_auth_proto_goTypes,
		DependencyIndexes: file_cinch_v1_auth_proto_depIdxs,
		MessageInfos:      file_cinch_v1_auth_proto_msgTypes,
	}.Build()
	File_cinch_v1_auth_proto = out.File
	file_cinch_v1_auth_proto_goTypes = nil
	file_cinch_v1_auth_proto_depIdxs = nil
}
