// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cinch/v1/clips.proto

package cinchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Clip struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ClipId      string                 `protobuf:"bytes,1,opt,name=clip_id,json=clipId,proto3" json:"clip_id,omitempty"`
	UserId      string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content     string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ContentType string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Source      string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Label       string                 `protobuf:"bytes,6,opt,name=label,proto3" json:"label,omitempty"`
	ByteSize    int64                  `protobuf:"varint,7,opt,name=byte_size,json=byteSize,proto3" json:"byte_size,omitempty"`
	MediaPath   *string                `protobuf:"bytes,8,opt,name=media_path,json=mediaPath,proto3,oneof" json:"media_path,omitempty"`
	CreatedAt   string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// field 10 (ttl) removed — do not reuse
	Encrypted     bool    `protobuf:"varint,11,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	IsPinned      bool    `protobuf:"varint,12,opt,name=is_pinned,json=isPinned,proto3" json:"is_pinned,omitempty"`
	PinNote       *string `protobuf:"bytes,13,opt,name=pin_note,json=pinNote,proto3,oneof" json:"pin_note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Clip) Reset() {
	*x = Clip{}
	mi := &file_cinch_v1_clips_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Clip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Clip) ProtoMessage() {}

func (x *Clip) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_clips_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Clip.ProtoReflect.Descriptor instead.
func (*Clip) Descriptor() ([]byte, []int) {
	return file_cinch_v1_clips_proto_rawDescGZIP(), []int{0}
}

func (x *Clip) GetClipId() string {
	if x != nil {
		return x.ClipId
	}
	return ""
}

func (x *Clip) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Clip) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Clip) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Clip) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Clip) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Clip) GetByteSize() int64 {
	if x != nil {
		return x.ByteSize
	}
	return 0
}

func (x *Clip) GetMediaPath() string {
	if x != nil && x.MediaPath != nil {
		return *x.MediaPath
	}
	return ""
}

func (x *Clip) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Clip) GetEncrypted() bool {
	if x != nil {
		return x.Encrypted
	}
	return false
}

func (x *Clip) GetIsPinned() bool {
	if x != nil {
		return x.IsPinned
	}
	return false
}

func (x *Clip) GetPinNote() string {
	if x != nil && x.PinNote != nil {
		return *x.PinNote
	}
	return ""
}

type PushClipRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Content     string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ContentType string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Label       string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Source      string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	// field 5 (ttl) removed — do not reuse
	ByteSize        int64   `protobuf:"varint,6,opt,name=byte_size,json=byteSize,proto3" json:"byte_size,omitempty"`
	Encrypted       bool    `protobuf:"varint,7,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	TargetDeviceId  *string `protobuf:"bytes,8,opt,name=target_device_id,json=targetDeviceId,proto3,oneof" json:"target_device_id,omitempty"`
	MediaPath       *string `protobuf:"bytes,9,opt,name=media_path,json=mediaPath,proto3,oneof" json:"media_path,omitempty"`
	ClientCreatedAt *string `protobuf:"bytes,10,opt,name=client_created_at,json=clientCreatedAt,proto3,oneof" json:"client_created_at,omitempty"` // RFC3339; relay clamps to [now-90d, now]
	IdempotencyKey  *string `protobuf:"bytes,11,opt,name=idempotency_key,json=idempotencyKey,proto3,oneof" json:"idempotency_key,omitempty"`      // (user_id, key) unique within 24h
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PushClipRequest) Reset() {
	*x = PushClipRequest{}
	mi := &file_cinch_v1_clips_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushClipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushClipRequest) ProtoMessage() {}

func (x *PushClipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_clips_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushClipRequest.ProtoReflect.Descriptor instead.
func (*PushClipRequest) Descriptor() ([]byte, []int) {
	return file_cinch_v1_clips_proto_rawDescGZIP(), []int{1}
}

func (x *PushClipRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PushClipRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *PushClipRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *PushClipRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PushClipRequest) GetByteSize() int64 {
	if x != nil {
		return x.ByteSize
	}
	return 0
}

func (x *PushClipRequest) GetEncrypted() bool {
	if x != nil {
		return x.Encrypted
	}
	return false
}

func (x *PushClipRequest) GetTargetDeviceId() string {
	if x != nil && x.TargetDeviceId != nil {
		return *x.TargetDeviceId
	}
	return ""
}

func (x *PushClipRequest) GetMediaPath() string {
	if x != nil && x.MediaPath != nil {
		return *x.MediaPath
	}
	return ""
}

func (x *PushClipRequest) GetClientCreatedAt() string {
	if x != nil && x.ClientCreatedAt != nil {
		return *x.ClientCreatedAt
	}
	return ""
}

func (x *PushClipRequest) GetIdempotencyKey() string {
	if x != nil && x.IdempotencyKey != nil {
		return *x.IdempotencyKey
	}
	return ""
}

type PushClipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClipId        string                 `protobuf:"bytes,1,opt,name=clip_id,json=clipId,proto3" json:"clip_id,omitempty"`
	ByteSize      int64                  `protobuf:"varint,2,opt,name=byte_size,json=byteSize,proto3" json:"byte_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushClipResponse) Reset() {
	*x = PushClipResponse{}
	mi := &file_cinch_v1_clips_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushClipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushClipResponse) ProtoMessage() {}

func (x *PushClipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_clips_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushClipResponse.ProtoReflect.Descriptor instead.
func (*PushClipResponse) Descriptor() ([]byte, []int) {
	return file_cinch_v1_clips_proto_rawDescGZIP(), []int{2}
}

func (x *PushClipResponse) GetClipId() string {
	if x != nil {
		return x.ClipId
	}
	return ""
}

func (x *PushClipResponse) GetByteSize() int64 {
	if x != nil {
		return x.ByteSize
	}
	return 0
}

type ListClipsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Since         string                 `protobuf:"bytes,1,opt,name=since,proto3" json:"since,omitempty"`                                      // RFC 3339 timestamp; empty = no filter (returns most recent)
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                                     // 0 = default (50), max 200
	SourceFilter  string                 `protobuf:"bytes,3,opt,name=source_filter,json=sourceFilter,proto3" json:"source_filter,omitempty"`    // resolved source key; empty = no filter
	ExcludeSource string                 `protobuf:"bytes,4,opt,name=exclude_source,json=excludeSource,proto3" json:"exclude_source,omitempty"` // resolved source key to exclude; empty = no exclusion
	ExcludeImage  bool                   `protobuf:"varint,5,opt,name=exclude_image,json=excludeImage,proto3" json:"exclude_image,omitempty"`   // when true, drop image clips
	ExcludeText   bool                   `protobuf:"varint,6,opt,name=exclude_text,json=excludeText,proto3" json:"exclude_text,omitempty"`      // when true, drop text clips
	ClipIds       []string               `protobuf:"bytes,7,rep,name=clip_ids,json=clipIds,proto3" json:"clip_ids,omitempty"`                   // when non-empty, return only these clips (max 200)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClipsRequest) Reset() {
	*x = ListClipsRequest{}
	mi := &file_cinch_v1_clips_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClipsRequest) ProtoMessage() {}

func (x *ListClipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_clips_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClipsRequest.ProtoReflect.Descriptor instead.
func (*ListClipsRequest) Descriptor() ([]byte, []int) {
	return file_cinch_v1_clips_proto_rawDescGZIP(), []int{3}
}

func (x *ListClipsRequest) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

func (x *ListClipsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListClipsRequest) GetSourceFilter() string {
	if x != nil {
		return x.SourceFilter
	}
	return ""
}

func (x *ListClipsRequest) GetExcludeSource() string {
	if x != nil {
		return x.ExcludeSource
	}
	return ""
}

func (x *ListClipsRequest) GetExcludeImage() bool {
	if x != nil {
		return x.ExcludeImage
	}
	return false
}

func (x *ListClipsRequest) GetExcludeText() bool {
	if x != nil {
		return x.ExcludeText
	}
	return false
}

func (x *ListClipsRequest) GetClipIds() []string {
	if x != nil {
		return x.ClipIds
	}
	return nil
}

type ListClipsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clips         []*Clip                `protobuf:"bytes,1,rep,name=clips,proto3" json:"clips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClipsResponse) Reset() {
	*x = ListClipsResponse{}
	mi := &file_cinch_v1_clips_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClipsResponse) ProtoMessage() {}

func (x *ListClipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_clips_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClipsResponse.ProtoReflect.Descriptor instead.
func (*ListClipsResponse) Descriptor() ([]byte, []int) {
	return file_cinch_v1_clips_proto_rawDescGZIP(), []int{4}
}

func (x *ListClipsResponse) GetClips() []*Clip {
	if x != nil {
		return x.Clips
	}
	return nil
}

type GetLatestClipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	ExcludeSource string                 `protobuf:"bytes,2,opt,name=exclude_source,json=excludeSource,proto3" json:"exclude_source,omitempty"` // when set, return latest clip whose source != exclude_source
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestClipRequest) Reset() {
	*x = GetLatestClipRequest{}
	mi := &file_cinch_v1_clips_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestClipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestClipRequest) ProtoMessage() {}

func (x *GetLatestClipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_clips_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestClipRequest.ProtoReflect.Descriptor instead.
func (*GetLatestClipRequest) Descriptor() ([]byte, []int) {
	return file_cinch_v1_clips_proto_rawDescGZIP(), []int{5}
}

func (x *GetLatestClipRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GetLatestClipRequest) GetExcludeSource() string {
	if x != nil {
		return x.ExcludeSource
	}
	return ""
}

type GetLatestClipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clip          *Clip                  `protobuf:"bytes,1,opt,name=clip,proto3" json:"clip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestClipResponse) Reset() {
	*x = GetLatestClipResponse{}
	mi := &file_cinch_v1_clips_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestClipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestClipResponse) ProtoMessage() {}

func (x *GetLatestClipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_clips_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestClipResponse.ProtoReflect.Descriptor instead.
func (*GetLatestClipResponse) Descriptor() ([]byte, []int) {
	return file_cinch_v1_clips_proto_rawDescGZIP(), []int{6}
}

func (x *GetLatestClipResponse) GetClip() *Clip {
	if x != nil {
		return x.Clip
	}
	return nil
}

type DeleteClipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClipId        string                 `protobuf:"bytes,1,opt,name=clip_id,json=clipId,proto3" json:"clip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClipRequest) Reset() {
	*x = DeleteClipRequest{}
	mi := &file_cinch_v1_clips_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClipRequest) ProtoMessage() {}

func (x *DeleteClipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_clips_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClipRequest.ProtoReflect.Descriptor instead.
func (*DeleteClipRequest) Descriptor() ([]byte, []int) {
	return file_cinch_v1_clips_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteClipRequest) GetClipId() string {
	if x != nil {
		return x.ClipId
	}
	return ""
}

type DeleteClipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClipResponse) Reset() {
	*x = DeleteClipResponse{}
	mi := &file_cinch_v1_clips_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClipResponse) ProtoMessage() {}

func (x *DeleteClipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_clips_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClipResponse.ProtoReflect.Descriptor instead.
func (*DeleteClipResponse) Descriptor() ([]byte, []int) {
	return file_cinch_v1_clips_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteClipResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_cinch_v1_clips_proto protoreflect.FileDescriptor

const file_cinch_v1_clips_proto_rawDesc = "" +
	"\n" +
	"\x14cinch/v1/clips.proto\x12\bcinch.v1\"\xfa\x02\n" +
	"\x04Clip\x12\x17\n" +
	"\aclip_id\x18\x01 \x01(\tR\x06clipId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x14\n" +
	"\x05label\x18\x06 \x01(\tR\x05label\x12\x1b\n" +
	"\tbyte_size\x18\a \x01(\x03R\bbyteSize\x12\"\n" +
	"\n" +
	"media_path\x18\b \x01(\tH\x00R\tmediaPath\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tencrypted\x18\v \x01(\bR\tencrypted\x12\x1b\n" +
	"\tis_pinned\x18\f \x01(\bR\bisPinned\x12\x1e\n" +
	"\bpin_note\x18\r \x01(\tH\x01R\apinNote\x88\x01\x01B\r\n" +
	"\v_media_pathB\v\n" +
	"\t_pin_note\"\xb7\x03\n" +
	"\x0fPushClipRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x1b\n" +
	"\tbyte_size\x18\x06 \x01(\x03R\bbyteSize\x12\x1c\n" +
	"\tencrypted\x18\a \x01(\bR\tencrypted\x12-\n" +
	"\x10target_device_id\x18\b \x01(\tH\x00R\x0etargetDeviceId\x88\x01\x01\x12\"\n" +
	"\n" +
	"media_path\x18\t \x01(\tH\x01R\tmediaPath\x88\x01\x01\x12/\n" +
	"\x11client_created_at\x18\n" +
	" \x01(\tH\x02R\x0fclientCreatedAt\x88\x01\x01\x12,\n" +
	"\x0fidempotency_key\x18\v \x01(\tH\x03R\x0eidempotencyKey\x88\x01\x01B\x13\n" +
	"\x11_target_device_idB\r\n" +
	"\v_media_pathB\x14\n" +
	"\x12_client_created_atB\x12\n" +
	"\x10_idempotency_key\"H\n" +
	"\x10PushClipResponse\x12\x17\n" +
	"\aclip_id\x18\x01 \x01(\tR\x06clipId\x12\x1b\n" +
	"\tbyte_size\x18\x02 \x01(\x03R\bbyteSize\"\xed\x01\n" +
	"\x10ListClipsRequest\x12\x14\n" +
	"\x05since\x18\x01 \x01(\tR\x05since\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12#\n" +
	"\rsource_filter\x18\x03 \x01(\tR\fsourceFilter\x12%\n" +
	"\x0eexclude_source\x18\x04 \x01(\tR\rexcludeSource\x12#\n" +
	"\rexclude_image\x18\x05 \x01(\bR\fexcludeImage\x12!\n" +
	"\fexclude_text\x18\x06 \x01(\bR\vexcludeText\x12\x19\n" +
	"\bclip_ids\x18\a \x03(\tR\aclipIds\"9\n" +
	"\x11ListClipsResponse\x12$\n" +
	"\x05clips\x18\x01 \x03(\v2\x0e.cinch.v1.ClipR\x05clips\"U\n" +
	"\x14GetLatestClipRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12%\n" +
	"\x0eexclude_source\x18\x02 \x01(\tR\rexcludeSource\";\n" +
	"\x15GetLatestClipResponse\x12\"\n" +
	"\x04clip\x18\x01 \x01(\v2\x0e.cinch.v1.ClipR\x04clip\",\n" +
	"\x11DeleteClipRequest\x12\x17\n" +
	"\aclip_id\x18\x01 \x01(\tR\x06clipId\"$\n" +
	"\x12DeleteClipResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xb2\x02\n" +
	"\fClipsService\x12A\n" +
	"\bPushClip\x12\x19.cinch.v1.PushClipRequest\x1a\x1a.cinch.v1.PushClipResponse\x12D\n" +
	"\tListClips\x12\x1a.cinch.v1.ListClipsRequest\x1a\x1b.cinch.v1.ListClipsResponse\x12P\n" +
	"\rGetLatestClip\x12\x1e.cinch.v1.GetLatestClipRequest\x1a\x1f.cinch.v1.GetLatestClipResponse\x12G\n" +
	"\n" +
	"DeleteClip\x12\x1b.cinch.v1.DeleteClipRequest\x1a\x1c.cinch.v1.DeleteClipResponseB4Z2github.com/cinchcli/relay/internal/cinchv1;cinchv1b\x06proto3"

var (
	file_cinch_v1_clips_proto_rawDescOnce sync.Once
	file_cinch_v1_clips_proto_rawDescData []byte
)

func file_cinch_v1_clips_proto_rawDescGZIP() []byte {
	file_cinch_v1_clips_proto_rawDescOnce.Do(func() {
		file_cinch_v1_clips_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cinch_v1_clips_proto_rawDesc), len(file_cinch_v1_clips_proto_rawDesc)))
	})
	return file_cinch_v1_clips_proto_rawDescData
}

var file_cinch_v1_clips_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cinch_v1_clips_proto_goTypes = []any{
	(*Clip)(nil),                  // 0: cinch.v1.Clip
	(*PushClipRequest)(nil),       // 1: cinch.v1.PushClipRequest
	(*PushClipResponse)(nil),      // 2: cinch.v1.PushClipResponse
	(*ListClipsRequest)(nil),      // 3: cinch.v1.ListClipsRequest
	(*ListClipsResponse)(nil),     // 4: cinch.v1.ListClipsResponse
	(*GetLatestClipRequest)(nil),  // 5: cinch.v1.GetLatestClipRequest
	(*GetLatestClipResponse)(nil), // 6: cinch.v1.GetLatestClipResponse
	(*DeleteClipRequest)(nil),     // 7: cinch.v1.DeleteClipRequest
	(*DeleteClipResponse)(nil),    // 8: cinch.v1.DeleteClipResponse
}
var file_cinch_v1_clips_proto_depIdxs = []int32{
	0, // 0: cinch.v1.ListClipsResponse.clips:type_name -> cinch.v1.Clip
	0, // 1: cinch.v1.GetLatestClipResponse.clip:type_name -> cinch.v1.Clip
	1, // 2: cinch.v1.ClipsService.PushClip:input_type -> cinch.v1.PushClipRequest
	3, // 3: cinch.v1.ClipsService.ListClips:input_type -> cinch.v1.ListClipsRequest
	5, // 4: cinch.v1.ClipsService.GetLatestClip:input_type -> cinch.v1.GetLatestClipRequest
	7, // 5: cinch.v1.ClipsService.DeleteClip:input_type -> cinch.v1.DeleteClipRequest
	2, // 6: cinch.v1.ClipsService.PushClip:output_type -> cinch.v1.PushClipResponse
	4, // 7: cinch.v1.ClipsService.ListClips:output_type -> cinch.v1.ListClipsResponse
	6, // 8: cinch.v1.ClipsService.GetLatestClip:output_type -> cinch.v1.GetLatestClipResponse
	8, // 9: cinch.v1.ClipsService.DeleteClip:output_type -> cinch.v1.DeleteClipResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cinch_v1_clips_proto_init() }
func file_cinch_v1_clips_proto_init() {
	if File_cinch_v1_clips_proto != nil {
		return
	}
	file_cinch_v1_clips_proto_msgTypes[0].OneofWrappers = []any{}
	file_cinch_v1_clips_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cinch_v1_clips_proto_rawDesc), len(file_cinch_v1_clips_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cinch_v1_clips_proto_goTypes,
		DependencyIndexes: file_cinch_v1_clips_proto_depIdxs,
		MessageInfos:      file_cinch_v1_clips_proto_msgTypes,
	}.Build()
	File_cinch_v1_clips_proto = out.File
	file_cinch_v1_clips_proto_goTypes = nil
	file_cinch_v1_clips_proto_depIdxs = nil
}
