// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cinch/v1/devices.proto

package cinchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Device struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hostname             string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	SourceKey            string                 `protobuf:"bytes,3,opt,name=source_key,json=sourceKey,proto3" json:"source_key,omitempty"`
	ClipCount            int32                  `protobuf:"varint,4,opt,name=clip_count,json=clipCount,proto3" json:"clip_count,omitempty"`
	PairedAt             string                 `protobuf:"bytes,5,opt,name=paired_at,json=pairedAt,proto3" json:"paired_at,omitempty"`
	LastPushAt           *string                `protobuf:"bytes,6,opt,name=last_push_at,json=lastPushAt,proto3,oneof" json:"last_push_at,omitempty"`
	Online               bool                   `protobuf:"varint,7,opt,name=online,proto3" json:"online,omitempty"`
	Nickname             string                 `protobuf:"bytes,8,opt,name=nickname,proto3" json:"nickname,omitempty"`
	PublicKey            string                 `protobuf:"bytes,9,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PublicKeyFingerprint string                 `protobuf:"bytes,10,opt,name=public_key_fingerprint,json=publicKeyFingerprint,proto3" json:"public_key_fingerprint,omitempty"`
	MachineId            *string                `protobuf:"bytes,11,opt,name=machine_id,json=machineId,proto3,oneof" json:"machine_id,omitempty"`
	// Semver string of the client binary as reported via WS client_hello or
	// X-Cinch-Client-Version. Empty if the device has not reported yet.
	ClientVersion *string `protobuf:"bytes,12,opt,name=client_version,json=clientVersion,proto3,oneof" json:"client_version,omitempty"`
	// "cli" or "desktop". Determines which GitHub repo's latest release to
	// compare against. Empty if not reported.
	ClientType *string `protobuf:"bytes,13,opt,name=client_type,json=clientType,proto3,oneof" json:"client_type,omitempty"`
	// RFC3339 timestamp of the last version report.
	ClientVersionAt *string `protobuf:"bytes,14,opt,name=client_version_at,json=clientVersionAt,proto3,oneof" json:"client_version_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_cinch_v1_devices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_devices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_cinch_v1_devices_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Device) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Device) GetSourceKey() string {
	if x != nil {
		return x.SourceKey
	}
	return ""
}

func (x *Device) GetClipCount() int32 {
	if x != nil {
		return x.ClipCount
	}
	return 0
}

func (x *Device) GetPairedAt() string {
	if x != nil {
		return x.PairedAt
	}
	return ""
}

func (x *Device) GetLastPushAt() string {
	if x != nil && x.LastPushAt != nil {
		return *x.LastPushAt
	}
	return ""
}

func (x *Device) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *Device) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Device) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *Device) GetPublicKeyFingerprint() string {
	if x != nil {
		return x.PublicKeyFingerprint
	}
	return ""
}

func (x *Device) GetMachineId() string {
	if x != nil && x.MachineId != nil {
		return *x.MachineId
	}
	return ""
}

func (x *Device) GetClientVersion() string {
	if x != nil && x.ClientVersion != nil {
		return *x.ClientVersion
	}
	return ""
}

func (x *Device) GetClientType() string {
	if x != nil && x.ClientType != nil {
		return *x.ClientType
	}
	return ""
}

func (x *Device) GetClientVersionAt() string {
	if x != nil && x.ClientVersionAt != nil {
		return *x.ClientVersionAt
	}
	return ""
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_cinch_v1_devices_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_devices_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_cinch_v1_devices_proto_rawDescGZIP(), []int{1}
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*Device              `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_cinch_v1_devices_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_devices_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_cinch_v1_devices_proto_rawDescGZIP(), []int{2}
}

func (x *ListDevicesResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

type SetNicknameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNicknameRequest) Reset() {
	*x = SetNicknameRequest{}
	mi := &file_cinch_v1_devices_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNicknameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNicknameRequest) ProtoMessage() {}

func (x *SetNicknameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_devices_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNicknameRequest.ProtoReflect.Descriptor instead.
func (*SetNicknameRequest) Descriptor() ([]byte, []int) {
	return file_cinch_v1_devices_proto_rawDescGZIP(), []int{3}
}

func (x *SetNicknameRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SetNicknameRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type SetNicknameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNicknameResponse) Reset() {
	*x = SetNicknameResponse{}
	mi := &file_cinch_v1_devices_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNicknameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNicknameResponse) ProtoMessage() {}

func (x *SetNicknameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_devices_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNicknameResponse.ProtoReflect.Descriptor instead.
func (*SetNicknameResponse) Descriptor() ([]byte, []int) {
	return file_cinch_v1_devices_proto_rawDescGZIP(), []int{4}
}

func (x *SetNicknameResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type SetRetentionRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RemoteRetentionDays int32                  `protobuf:"varint,1,opt,name=remote_retention_days,json=remoteRetentionDays,proto3" json:"remote_retention_days,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SetRetentionRequest) Reset() {
	*x = SetRetentionRequest{}
	mi := &file_cinch_v1_devices_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRetentionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRetentionRequest) ProtoMessage() {}

func (x *SetRetentionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_devices_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRetentionRequest.ProtoReflect.Descriptor instead.
func (*SetRetentionRequest) Descriptor() ([]byte, []int) {
	return file_cinch_v1_devices_proto_rawDescGZIP(), []int{5}
}

func (x *SetRetentionRequest) GetRemoteRetentionDays() int32 {
	if x != nil {
		return x.RemoteRetentionDays
	}
	return 0
}

type SetRetentionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRetentionResponse) Reset() {
	*x = SetRetentionResponse{}
	mi := &file_cinch_v1_devices_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRetentionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRetentionResponse) ProtoMessage() {}

func (x *SetRetentionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_devices_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRetentionResponse.ProtoReflect.Descriptor instead.
func (*SetRetentionResponse) Descriptor() ([]byte, []int) {
	return file_cinch_v1_devices_proto_rawDescGZIP(), []int{6}
}

func (x *SetRetentionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_cinch_v1_devices_proto protoreflect.FileDescriptor

const file_cinch_v1_devices_proto_rawDesc = "" +
	"\n" +
	"\x16cinch/v1/devices.proto\x12\bcinch.v1\"\xbf\x04\n" +
	"\x06Device\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"source_key\x18\x03 \x01(\tR\tsourceKey\x12\x1d\n" +
	"\n" +
	"clip_count\x18\x04 \x01(\x05R\tclipCount\x12\x1b\n" +
	"\tpaired_at\x18\x05 \x01(\tR\bpairedAt\x12%\n" +
	"\flast_push_at\x18\x06 \x01(\tH\x00R\n" +
	"lastPushAt\x88\x01\x01\x12\x16\n" +
	"\x06online\x18\a \x01(\bR\x06online\x12\x1a\n" +
	"\bnickname\x18\b \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"public_key\x18\t \x01(\tR\tpublicKey\x124\n" +
	"\x16public_key_fingerprint\x18\n" +
	" \x01(\tR\x14publicKeyFingerprint\x12\"\n" +
	"\n" +
	"machine_id\x18\v \x01(\tH\x01R\tmachineId\x88\x01\x01\x12*\n" +
	"\x0eclient_version\x18\f \x01(\tH\x02R\rclientVersion\x88\x01\x01\x12$\n" +
	"\vclient_type\x18\r \x01(\tH\x03R\n" +
	"clientType\x88\x01\x01\x12/\n" +
	"\x11client_version_at\x18\x0e \x01(\tH\x04R\x0fclientVersionAt\x88\x01\x01B\x0f\n" +
	"\r_last_push_atB\r\n" +
	"\v_machine_idB\x11\n" +
	"\x0f_client_versionB\x0e\n" +
	"\f_client_typeB\x14\n" +
	"\x12_client_version_at\"\x14\n" +
	"\x12ListDevicesRequest\"A\n" +
	"\x13ListDevicesResponse\x12*\n" +
	"\adevices\x18\x01 \x03(\v2\x10.cinch.v1.DeviceR\adevices\"M\n" +
	"\x12SetNicknameRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\"%\n" +
	"\x13SetNicknameResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"I\n" +
	"\x13SetRetentionRequest\x122\n" +
	"\x15remote_retention_days\x18\x01 \x01(\x05R\x13remoteRetentionDays\"&\n" +
	"\x14SetRetentionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xf7\x01\n" +
	"\x0eDevicesService\x12J\n" +
	"\vListDevices\x12\x1c.cinch.v1.ListDevicesRequest\x1a\x1d.cinch.v1.ListDevicesResponse\x12J\n" +
	"\vSetNickname\x12\x1c.cinch.v1.SetNicknameRequest\x1a\x1d.cinch.v1.SetNicknameResponse\x12M\n" +
	"\fSetRetention\x12\x1d.cinch.v1.SetRetentionRequest\x1a\x1e.cinch.v1.SetRetentionResponseB4Z2github.com/cinchcli/relay/internal/cinchv1;cinchv1b\x06proto3"

var (
	file_cinch_v1_devices_proto_rawDescOnce sync.Once
	file_cinch_v1_devices_proto_rawDescData []byte
)

func file_cinch_v1_devices_proto_rawDescGZIP() []byte {
	file_cinch_v1_devices_proto_rawDescOnce.Do(func() {
		file_cinch_v1_devices_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cinch_v1_devices_proto_rawDesc), len(file_cinch_v1_devices_proto_rawDesc)))
	})
	return file_cinch_v1_devices_proto_rawDescData
}

var file_cinch_v1_devices_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cinch_v1_devices_proto_goTypes = []any{
	(*Device)(nil),               // 0: cinch.v1.Device
	(*ListDevicesRequest)(nil),   // 1: cinch.v1.ListDevicesRequest
	(*ListDevicesResponse)(nil),  // 2: cinch.v1.ListDevicesResponse
	(*SetNicknameRequest)(nil),   // 3: cinch.v1.SetNicknameRequest
	(*SetNicknameResponse)(nil),  // 4: cinch.v1.SetNicknameResponse
	(*SetRetentionRequest)(nil),  // 5: cinch.v1.SetRetentionRequest
	(*SetRetentionResponse)(nil), // 6: cinch.v1.SetRetentionResponse
}
var file_cinch_v1_devices_proto_depIdxs = []int32{
	0, // 0: cinch.v1.ListDevicesResponse.devices:type_name -> cinch.v1.Device
	1, // 1: cinch.v1.DevicesService.ListDevices:input_type -> cinch.v1.ListDevicesRequest
	3, // 2: cinch.v1.DevicesService.SetNickname:input_type -> cinch.v1.SetNicknameRequest
	5, // 3: cinch.v1.DevicesService.SetRetention:input_type -> cinch.v1.SetRetentionRequest
	2, // 4: cinch.v1.DevicesService.ListDevices:output_type -> cinch.v1.ListDevicesResponse
	4, // 5: cinch.v1.DevicesService.SetNickname:output_type -> cinch.v1.SetNicknameResponse
	6, // 6: cinch.v1.DevicesService.SetRetention:output_type -> cinch.v1.SetRetentionResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cinch_v1_devices_proto_init() }
func file_cinch_v1_devices_proto_init() {
	if File_cinch_v1_devices_proto != nil {
		return
	}
	file_cinch_v1_devices_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cinch_v1_devices_proto_rawDesc), len(file_cinch_v1_devices_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cinch_v1_devices_proto_goTypes,
		DependencyIndexes: file_cinch_v1_devices_proto_depIdxs,
		MessageInfos:      file_cinch_v1_devices_proto_msgTypes,
	}.Build()
	File_cinch_v1_devices_proto = out.File
	file_cinch_v1_devices_proto_goTypes = nil
	file_cinch_v1_devices_proto_depIdxs = nil
}
