// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cinch/v1/me.proto

package cinchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeRequest) Reset() {
	*x = GetMeRequest{}
	mi := &file_cinch_v1_me_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeRequest) ProtoMessage() {}

func (x *GetMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_me_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeRequest.ProtoReflect.Descriptor instead.
func (*GetMeRequest) Descriptor() ([]byte, []int) {
	return file_cinch_v1_me_proto_rawDescGZIP(), []int{0}
}

type GetMeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The plan the user is currently on. "free" if no user_capabilities row
	// exists. Otherwise derived from the caps (see plan_name in relay).
	PlanName string `protobuf:"bytes,1,opt,name=plan_name,json=planName,proto3" json:"plan_name,omitempty"`
	// Caps applied to this user. Zero means "unlimited" / unset.
	Plan *Plan `protobuf:"bytes,2,opt,name=plan,proto3" json:"plan,omitempty"`
	// Current usage measured server-side.
	Usage         *Usage `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeResponse) Reset() {
	*x = GetMeResponse{}
	mi := &file_cinch_v1_me_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeResponse) ProtoMessage() {}

func (x *GetMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_me_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeResponse.ProtoReflect.Descriptor instead.
func (*GetMeResponse) Descriptor() ([]byte, []int) {
	return file_cinch_v1_me_proto_rawDescGZIP(), []int{1}
}

func (x *GetMeResponse) GetPlanName() string {
	if x != nil {
		return x.PlanName
	}
	return ""
}

func (x *GetMeResponse) GetPlan() *Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *GetMeResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type Plan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceLimit   int32                  `protobuf:"varint,1,opt,name=device_limit,json=deviceLimit,proto3" json:"device_limit,omitempty"`       // 0 = unlimited
	RetentionDays int32                  `protobuf:"varint,2,opt,name=retention_days,json=retentionDays,proto3" json:"retention_days,omitempty"` // 0 = unlimited
	RateLimit     int32                  `protobuf:"varint,3,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`             // 0 = unset (requests/day)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plan) Reset() {
	*x = Plan{}
	mi := &file_cinch_v1_me_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_me_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_cinch_v1_me_proto_rawDescGZIP(), []int{2}
}

func (x *Plan) GetDeviceLimit() int32 {
	if x != nil {
		return x.DeviceLimit
	}
	return 0
}

func (x *Plan) GetRetentionDays() int32 {
	if x != nil {
		return x.RetentionDays
	}
	return 0
}

func (x *Plan) GetRateLimit() int32 {
	if x != nil {
		return x.RateLimit
	}
	return 0
}

type Usage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveDevices int32                  `protobuf:"varint,1,opt,name=active_devices,json=activeDevices,proto3" json:"active_devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_cinch_v1_me_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_cinch_v1_me_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_cinch_v1_me_proto_rawDescGZIP(), []int{3}
}

func (x *Usage) GetActiveDevices() int32 {
	if x != nil {
		return x.ActiveDevices
	}
	return 0
}

var File_cinch_v1_me_proto protoreflect.FileDescriptor

const file_cinch_v1_me_proto_rawDesc = "" +
	"\n" +
	"\x11cinch/v1/me.proto\x12\bcinch.v1\"\x0e\n" +
	"\fGetMeRequest\"w\n" +
	"\rGetMeResponse\x12\x1b\n" +
	"\tplan_name\x18\x01 \x01(\tR\bplanName\x12\"\n" +
	"\x04plan\x18\x02 \x01(\v2\x0e.cinch.v1.PlanR\x04plan\x12%\n" +
	"\x05usage\x18\x03 \x01(\v2\x0f.cinch.v1.UsageR\x05usage\"o\n" +
	"\x04Plan\x12!\n" +
	"\fdevice_limit\x18\x01 \x01(\x05R\vdeviceLimit\x12%\n" +
	"\x0eretention_days\x18\x02 \x01(\x05R\rretentionDays\x12\x1d\n" +
	"\n" +
	"rate_limit\x18\x03 \x01(\x05R\trateLimit\".\n" +
	"\x05Usage\x12%\n" +
	"\x0eactive_devices\x18\x01 \x01(\x05R\ractiveDevices2E\n" +
	"\tMeService\x128\n" +
	"\x05GetMe\x12\x16.cinch.v1.GetMeRequest\x1a\x17.cinch.v1.GetMeResponseB4Z2github.com/cinchcli/relay/internal/cinchv1;cinchv1b\x06proto3"

var (
	file_cinch_v1_me_proto_rawDescOnce sync.Once
	file_cinch_v1_me_proto_rawDescData []byte
)

func file_cinch_v1_me_proto_rawDescGZIP() []byte {
	file_cinch_v1_me_proto_rawDescOnce.Do(func() {
		file_cinch_v1_me_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cinch_v1_me_proto_rawDesc), len(file_cinch_v1_me_proto_rawDesc)))
	})
	return file_cinch_v1_me_proto_rawDescData
}

var file_cinch_v1_me_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cinch_v1_me_proto_goTypes = []any{
	(*GetMeRequest)(nil),  // 0: cinch.v1.GetMeRequest
	(*GetMeResponse)(nil), // 1: cinch.v1.GetMeResponse
	(*Plan)(nil),          // 2: cinch.v1.Plan
	(*Usage)(nil),         // 3: cinch.v1.Usage
}
var file_cinch_v1_me_proto_depIdxs = []int32{
	2, // 0: cinch.v1.GetMeResponse.plan:type_name -> cinch.v1.Plan
	3, // 1: cinch.v1.GetMeResponse.usage:type_name -> cinch.v1.Usage
	0, // 2: cinch.v1.MeService.GetMe:input_type -> cinch.v1.GetMeRequest
	1, // 3: cinch.v1.MeService.GetMe:output_type -> cinch.v1.GetMeResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cinch_v1_me_proto_init() }
func file_cinch_v1_me_proto_init() {
	if File_cinch_v1_me_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cinch_v1_me_proto_rawDesc), len(file_cinch_v1_me_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cinch_v1_me_proto_goTypes,
		DependencyIndexes: file_cinch_v1_me_proto_depIdxs,
		MessageInfos:      file_cinch_v1_me_proto_msgTypes,
	}.Build()
	File_cinch_v1_me_proto = out.File
	file_cinch_v1_me_proto_goTypes = nil
	file_cinch_v1_me_proto_depIdxs = nil
}
