// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: cinch/v1/auth.proto

package cinchv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	cinchv1 "github.com/cinchcli/relay/internal/cinchv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "cinch.v1.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceLoginProcedure is the fully-qualified name of the AuthService's Login RPC.
	AuthServiceLoginProcedure = "/cinch.v1.AuthService/Login"
	// AuthServiceDeviceCodeStartProcedure is the fully-qualified name of the AuthService's
	// DeviceCodeStart RPC.
	AuthServiceDeviceCodeStartProcedure = "/cinch.v1.AuthService/DeviceCodeStart"
	// AuthServiceDeviceCodePollProcedure is the fully-qualified name of the AuthService's
	// DeviceCodePoll RPC.
	AuthServiceDeviceCodePollProcedure = "/cinch.v1.AuthService/DeviceCodePoll"
	// AuthServiceDeviceCodeCompleteProcedure is the fully-qualified name of the AuthService's
	// DeviceCodeComplete RPC.
	AuthServiceDeviceCodeCompleteProcedure = "/cinch.v1.AuthService/DeviceCodeComplete"
	// AuthServiceDeviceCodeDenyProcedure is the fully-qualified name of the AuthService's
	// DeviceCodeDeny RPC.
	AuthServiceDeviceCodeDenyProcedure = "/cinch.v1.AuthService/DeviceCodeDeny"
	// AuthServiceRevokeDeviceProcedure is the fully-qualified name of the AuthService's RevokeDevice
	// RPC.
	AuthServiceRevokeDeviceProcedure = "/cinch.v1.AuthService/RevokeDevice"
	// AuthServiceKeyBundlePutProcedure is the fully-qualified name of the AuthService's KeyBundlePut
	// RPC.
	AuthServiceKeyBundlePutProcedure = "/cinch.v1.AuthService/KeyBundlePut"
	// AuthServiceKeyBundleGetProcedure is the fully-qualified name of the AuthService's KeyBundleGet
	// RPC.
	AuthServiceKeyBundleGetProcedure = "/cinch.v1.AuthService/KeyBundleGet"
	// AuthServiceKeyBundleRetryProcedure is the fully-qualified name of the AuthService's
	// KeyBundleRetry RPC.
	AuthServiceKeyBundleRetryProcedure = "/cinch.v1.AuthService/KeyBundleRetry"
	// AuthServiceRegisterDevicePublicKeyProcedure is the fully-qualified name of the AuthService's
	// RegisterDevicePublicKey RPC.
	AuthServiceRegisterDevicePublicKeyProcedure = "/cinch.v1.AuthService/RegisterDevicePublicKey"
	// AuthServiceSetDisplayNameProcedure is the fully-qualified name of the AuthService's
	// SetDisplayName RPC.
	AuthServiceSetDisplayNameProcedure = "/cinch.v1.AuthService/SetDisplayName"
)

// AuthServiceClient is a client for the cinch.v1.AuthService service.
type AuthServiceClient interface {
	// Login creates a new anonymous account and returns its credentials.
	// Mirrors POST /auth/login — no auth required.
	Login(context.Context, *connect.Request[cinchv1.LoginRequest]) (*connect.Response[cinchv1.LoginResponse], error)
	// DeviceCodeStart initiates the device-code OAuth flow.
	// Mirrors POST /auth/device-code — no auth required.
	DeviceCodeStart(context.Context, *connect.Request[cinchv1.DeviceCodeStartRequest]) (*connect.Response[cinchv1.DeviceCodeStartResponse], error)
	// DeviceCodePoll polls a device code for completion.
	// Mirrors GET /auth/device-code/poll — no auth required.
	DeviceCodePoll(context.Context, *connect.Request[cinchv1.DeviceCodePollRequest]) (*connect.Response[cinchv1.DeviceCodePollResponse], error)
	// DeviceCodeComplete marks a device code as approved.
	// Mirrors POST /auth/device-code/complete — auth required.
	DeviceCodeComplete(context.Context, *connect.Request[cinchv1.DeviceCodeCompleteRequest]) (*connect.Response[cinchv1.DeviceCodeCompleteResponse], error)
	// DeviceCodeDeny rejects a pending device-code from an already-signed-in
	// device. The remote CLI's next DeviceCodePoll returns status="denied".
	// Mirrors POST /auth/device-code/deny — auth required.
	DeviceCodeDeny(context.Context, *connect.Request[cinchv1.DeviceCodeDenyRequest]) (*connect.Response[cinchv1.DeviceCodeDenyResponse], error)
	// RevokeDevice revokes a paired device by ID.
	// Mirrors POST /auth/device/revoke — auth required.
	RevokeDevice(context.Context, *connect.Request[cinchv1.RevokeDeviceRequest]) (*connect.Response[cinchv1.RevokeDeviceResponse], error)
	// KeyBundlePut stores an encrypted key bundle for a target device.
	// Mirrors POST /auth/key-bundle — auth required.
	KeyBundlePut(context.Context, *connect.Request[cinchv1.KeyBundlePutRequest]) (*connect.Response[cinchv1.KeyBundlePutResponse], error)
	// KeyBundleGet retrieves the encrypted key bundle for the calling device.
	// Mirrors GET /auth/key-bundle — auth required.
	KeyBundleGet(context.Context, *connect.Request[cinchv1.KeyBundleGetRequest]) (*connect.Response[cinchv1.KeyBundleGetResponse], error)
	// KeyBundleRetry asks the relay to re-broadcast key_exchange_requested
	// for the calling device. Used by `cinch auth retry-key`.
	// Mirrors POST /auth/key-bundle/retry — auth required.
	KeyBundleRetry(context.Context, *connect.Request[cinchv1.KeyBundleRetryRequest]) (*connect.Response[cinchv1.KeyBundleRetryResponse], error)
	// RegisterDevicePublicKey stores the X25519 public key for the calling
	// device so the relay can include it in ListPendingKeyExchanges sweeps
	// and broadcast key_exchange_requested for it. Called once after the
	// OAuth-only login flow finishes installing local credentials.
	// Mirrors POST /auth/device/public-key — auth required.
	RegisterDevicePublicKey(context.Context, *connect.Request[cinchv1.RegisterDevicePublicKeyRequest]) (*connect.Response[cinchv1.RegisterDevicePublicKeyResponse], error)
	// SetDisplayName updates `users.display_name` for the calling user. The
	// value overrides any OAuth-fetched display name on subsequent
	// DeviceCodePoll responses. A blank name returns InvalidArgument.
	// Mirrors POST /auth/display-name — auth required.
	SetDisplayName(context.Context, *connect.Request[cinchv1.SetDisplayNameRequest]) (*connect.Response[cinchv1.SetDisplayNameResponse], error)
}

// NewAuthServiceClient constructs a client for the cinch.v1.AuthService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := cinchv1.File_cinch_v1_auth_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		login: connect.NewClient[cinchv1.LoginRequest, cinchv1.LoginResponse](
			httpClient,
			baseURL+AuthServiceLoginProcedure,
			connect.WithSchema(authServiceMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
		deviceCodeStart: connect.NewClient[cinchv1.DeviceCodeStartRequest, cinchv1.DeviceCodeStartResponse](
			httpClient,
			baseURL+AuthServiceDeviceCodeStartProcedure,
			connect.WithSchema(authServiceMethods.ByName("DeviceCodeStart")),
			connect.WithClientOptions(opts...),
		),
		deviceCodePoll: connect.NewClient[cinchv1.DeviceCodePollRequest, cinchv1.DeviceCodePollResponse](
			httpClient,
			baseURL+AuthServiceDeviceCodePollProcedure,
			connect.WithSchema(authServiceMethods.ByName("DeviceCodePoll")),
			connect.WithClientOptions(opts...),
		),
		deviceCodeComplete: connect.NewClient[cinchv1.DeviceCodeCompleteRequest, cinchv1.DeviceCodeCompleteResponse](
			httpClient,
			baseURL+AuthServiceDeviceCodeCompleteProcedure,
			connect.WithSchema(authServiceMethods.ByName("DeviceCodeComplete")),
			connect.WithClientOptions(opts...),
		),
		deviceCodeDeny: connect.NewClient[cinchv1.DeviceCodeDenyRequest, cinchv1.DeviceCodeDenyResponse](
			httpClient,
			baseURL+AuthServiceDeviceCodeDenyProcedure,
			connect.WithSchema(authServiceMethods.ByName("DeviceCodeDeny")),
			connect.WithClientOptions(opts...),
		),
		revokeDevice: connect.NewClient[cinchv1.RevokeDeviceRequest, cinchv1.RevokeDeviceResponse](
			httpClient,
			baseURL+AuthServiceRevokeDeviceProcedure,
			connect.WithSchema(authServiceMethods.ByName("RevokeDevice")),
			connect.WithClientOptions(opts...),
		),
		keyBundlePut: connect.NewClient[cinchv1.KeyBundlePutRequest, cinchv1.KeyBundlePutResponse](
			httpClient,
			baseURL+AuthServiceKeyBundlePutProcedure,
			connect.WithSchema(authServiceMethods.ByName("KeyBundlePut")),
			connect.WithClientOptions(opts...),
		),
		keyBundleGet: connect.NewClient[cinchv1.KeyBundleGetRequest, cinchv1.KeyBundleGetResponse](
			httpClient,
			baseURL+AuthServiceKeyBundleGetProcedure,
			connect.WithSchema(authServiceMethods.ByName("KeyBundleGet")),
			connect.WithClientOptions(opts...),
		),
		keyBundleRetry: connect.NewClient[cinchv1.KeyBundleRetryRequest, cinchv1.KeyBundleRetryResponse](
			httpClient,
			baseURL+AuthServiceKeyBundleRetryProcedure,
			connect.WithSchema(authServiceMethods.ByName("KeyBundleRetry")),
			connect.WithClientOptions(opts...),
		),
		registerDevicePublicKey: connect.NewClient[cinchv1.RegisterDevicePublicKeyRequest, cinchv1.RegisterDevicePublicKeyResponse](
			httpClient,
			baseURL+AuthServiceRegisterDevicePublicKeyProcedure,
			connect.WithSchema(authServiceMethods.ByName("RegisterDevicePublicKey")),
			connect.WithClientOptions(opts...),
		),
		setDisplayName: connect.NewClient[cinchv1.SetDisplayNameRequest, cinchv1.SetDisplayNameResponse](
			httpClient,
			baseURL+AuthServiceSetDisplayNameProcedure,
			connect.WithSchema(authServiceMethods.ByName("SetDisplayName")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	login                   *connect.Client[cinchv1.LoginRequest, cinchv1.LoginResponse]
	deviceCodeStart         *connect.Client[cinchv1.DeviceCodeStartRequest, cinchv1.DeviceCodeStartResponse]
	deviceCodePoll          *connect.Client[cinchv1.DeviceCodePollRequest, cinchv1.DeviceCodePollResponse]
	deviceCodeComplete      *connect.Client[cinchv1.DeviceCodeCompleteRequest, cinchv1.DeviceCodeCompleteResponse]
	deviceCodeDeny          *connect.Client[cinchv1.DeviceCodeDenyRequest, cinchv1.DeviceCodeDenyResponse]
	revokeDevice            *connect.Client[cinchv1.RevokeDeviceRequest, cinchv1.RevokeDeviceResponse]
	keyBundlePut            *connect.Client[cinchv1.KeyBundlePutRequest, cinchv1.KeyBundlePutResponse]
	keyBundleGet            *connect.Client[cinchv1.KeyBundleGetRequest, cinchv1.KeyBundleGetResponse]
	keyBundleRetry          *connect.Client[cinchv1.KeyBundleRetryRequest, cinchv1.KeyBundleRetryResponse]
	registerDevicePublicKey *connect.Client[cinchv1.RegisterDevicePublicKeyRequest, cinchv1.RegisterDevicePublicKeyResponse]
	setDisplayName          *connect.Client[cinchv1.SetDisplayNameRequest, cinchv1.SetDisplayNameResponse]
}

// Login calls cinch.v1.AuthService.Login.
func (c *authServiceClient) Login(ctx context.Context, req *connect.Request[cinchv1.LoginRequest]) (*connect.Response[cinchv1.LoginResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// DeviceCodeStart calls cinch.v1.AuthService.DeviceCodeStart.
func (c *authServiceClient) DeviceCodeStart(ctx context.Context, req *connect.Request[cinchv1.DeviceCodeStartRequest]) (*connect.Response[cinchv1.DeviceCodeStartResponse], error) {
	return c.deviceCodeStart.CallUnary(ctx, req)
}

// DeviceCodePoll calls cinch.v1.AuthService.DeviceCodePoll.
func (c *authServiceClient) DeviceCodePoll(ctx context.Context, req *connect.Request[cinchv1.DeviceCodePollRequest]) (*connect.Response[cinchv1.DeviceCodePollResponse], error) {
	return c.deviceCodePoll.CallUnary(ctx, req)
}

// DeviceCodeComplete calls cinch.v1.AuthService.DeviceCodeComplete.
func (c *authServiceClient) DeviceCodeComplete(ctx context.Context, req *connect.Request[cinchv1.DeviceCodeCompleteRequest]) (*connect.Response[cinchv1.DeviceCodeCompleteResponse], error) {
	return c.deviceCodeComplete.CallUnary(ctx, req)
}

// DeviceCodeDeny calls cinch.v1.AuthService.DeviceCodeDeny.
func (c *authServiceClient) DeviceCodeDeny(ctx context.Context, req *connect.Request[cinchv1.DeviceCodeDenyRequest]) (*connect.Response[cinchv1.DeviceCodeDenyResponse], error) {
	return c.deviceCodeDeny.CallUnary(ctx, req)
}

// RevokeDevice calls cinch.v1.AuthService.RevokeDevice.
func (c *authServiceClient) RevokeDevice(ctx context.Context, req *connect.Request[cinchv1.RevokeDeviceRequest]) (*connect.Response[cinchv1.RevokeDeviceResponse], error) {
	return c.revokeDevice.CallUnary(ctx, req)
}

// KeyBundlePut calls cinch.v1.AuthService.KeyBundlePut.
func (c *authServiceClient) KeyBundlePut(ctx context.Context, req *connect.Request[cinchv1.KeyBundlePutRequest]) (*connect.Response[cinchv1.KeyBundlePutResponse], error) {
	return c.keyBundlePut.CallUnary(ctx, req)
}

// KeyBundleGet calls cinch.v1.AuthService.KeyBundleGet.
func (c *authServiceClient) KeyBundleGet(ctx context.Context, req *connect.Request[cinchv1.KeyBundleGetRequest]) (*connect.Response[cinchv1.KeyBundleGetResponse], error) {
	return c.keyBundleGet.CallUnary(ctx, req)
}

// KeyBundleRetry calls cinch.v1.AuthService.KeyBundleRetry.
func (c *authServiceClient) KeyBundleRetry(ctx context.Context, req *connect.Request[cinchv1.KeyBundleRetryRequest]) (*connect.Response[cinchv1.KeyBundleRetryResponse], error) {
	return c.keyBundleRetry.CallUnary(ctx, req)
}

// RegisterDevicePublicKey calls cinch.v1.AuthService.RegisterDevicePublicKey.
func (c *authServiceClient) RegisterDevicePublicKey(ctx context.Context, req *connect.Request[cinchv1.RegisterDevicePublicKeyRequest]) (*connect.Response[cinchv1.RegisterDevicePublicKeyResponse], error) {
	return c.registerDevicePublicKey.CallUnary(ctx, req)
}

// SetDisplayName calls cinch.v1.AuthService.SetDisplayName.
func (c *authServiceClient) SetDisplayName(ctx context.Context, req *connect.Request[cinchv1.SetDisplayNameRequest]) (*connect.Response[cinchv1.SetDisplayNameResponse], error) {
	return c.setDisplayName.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the cinch.v1.AuthService service.
type AuthServiceHandler interface {
	// Login creates a new anonymous account and returns its credentials.
	// Mirrors POST /auth/login — no auth required.
	Login(context.Context, *connect.Request[cinchv1.LoginRequest]) (*connect.Response[cinchv1.LoginResponse], error)
	// DeviceCodeStart initiates the device-code OAuth flow.
	// Mirrors POST /auth/device-code — no auth required.
	DeviceCodeStart(context.Context, *connect.Request[cinchv1.DeviceCodeStartRequest]) (*connect.Response[cinchv1.DeviceCodeStartResponse], error)
	// DeviceCodePoll polls a device code for completion.
	// Mirrors GET /auth/device-code/poll — no auth required.
	DeviceCodePoll(context.Context, *connect.Request[cinchv1.DeviceCodePollRequest]) (*connect.Response[cinchv1.DeviceCodePollResponse], error)
	// DeviceCodeComplete marks a device code as approved.
	// Mirrors POST /auth/device-code/complete — auth required.
	DeviceCodeComplete(context.Context, *connect.Request[cinchv1.DeviceCodeCompleteRequest]) (*connect.Response[cinchv1.DeviceCodeCompleteResponse], error)
	// DeviceCodeDeny rejects a pending device-code from an already-signed-in
	// device. The remote CLI's next DeviceCodePoll returns status="denied".
	// Mirrors POST /auth/device-code/deny — auth required.
	DeviceCodeDeny(context.Context, *connect.Request[cinchv1.DeviceCodeDenyRequest]) (*connect.Response[cinchv1.DeviceCodeDenyResponse], error)
	// RevokeDevice revokes a paired device by ID.
	// Mirrors POST /auth/device/revoke — auth required.
	RevokeDevice(context.Context, *connect.Request[cinchv1.RevokeDeviceRequest]) (*connect.Response[cinchv1.RevokeDeviceResponse], error)
	// KeyBundlePut stores an encrypted key bundle for a target device.
	// Mirrors POST /auth/key-bundle — auth required.
	KeyBundlePut(context.Context, *connect.Request[cinchv1.KeyBundlePutRequest]) (*connect.Response[cinchv1.KeyBundlePutResponse], error)
	// KeyBundleGet retrieves the encrypted key bundle for the calling device.
	// Mirrors GET /auth/key-bundle — auth required.
	KeyBundleGet(context.Context, *connect.Request[cinchv1.KeyBundleGetRequest]) (*connect.Response[cinchv1.KeyBundleGetResponse], error)
	// KeyBundleRetry asks the relay to re-broadcast key_exchange_requested
	// for the calling device. Used by `cinch auth retry-key`.
	// Mirrors POST /auth/key-bundle/retry — auth required.
	KeyBundleRetry(context.Context, *connect.Request[cinchv1.KeyBundleRetryRequest]) (*connect.Response[cinchv1.KeyBundleRetryResponse], error)
	// RegisterDevicePublicKey stores the X25519 public key for the calling
	// device so the relay can include it in ListPendingKeyExchanges sweeps
	// and broadcast key_exchange_requested for it. Called once after the
	// OAuth-only login flow finishes installing local credentials.
	// Mirrors POST /auth/device/public-key — auth required.
	RegisterDevicePublicKey(context.Context, *connect.Request[cinchv1.RegisterDevicePublicKeyRequest]) (*connect.Response[cinchv1.RegisterDevicePublicKeyResponse], error)
	// SetDisplayName updates `users.display_name` for the calling user. The
	// value overrides any OAuth-fetched display name on subsequent
	// DeviceCodePoll responses. A blank name returns InvalidArgument.
	// Mirrors POST /auth/display-name — auth required.
	SetDisplayName(context.Context, *connect.Request[cinchv1.SetDisplayNameRequest]) (*connect.Response[cinchv1.SetDisplayNameResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := cinchv1.File_cinch_v1_auth_proto.Services().ByName("AuthService").Methods()
	authServiceLoginHandler := connect.NewUnaryHandler(
		AuthServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(authServiceMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceDeviceCodeStartHandler := connect.NewUnaryHandler(
		AuthServiceDeviceCodeStartProcedure,
		svc.DeviceCodeStart,
		connect.WithSchema(authServiceMethods.ByName("DeviceCodeStart")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceDeviceCodePollHandler := connect.NewUnaryHandler(
		AuthServiceDeviceCodePollProcedure,
		svc.DeviceCodePoll,
		connect.WithSchema(authServiceMethods.ByName("DeviceCodePoll")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceDeviceCodeCompleteHandler := connect.NewUnaryHandler(
		AuthServiceDeviceCodeCompleteProcedure,
		svc.DeviceCodeComplete,
		connect.WithSchema(authServiceMethods.ByName("DeviceCodeComplete")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceDeviceCodeDenyHandler := connect.NewUnaryHandler(
		AuthServiceDeviceCodeDenyProcedure,
		svc.DeviceCodeDeny,
		connect.WithSchema(authServiceMethods.ByName("DeviceCodeDeny")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceRevokeDeviceHandler := connect.NewUnaryHandler(
		AuthServiceRevokeDeviceProcedure,
		svc.RevokeDevice,
		connect.WithSchema(authServiceMethods.ByName("RevokeDevice")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceKeyBundlePutHandler := connect.NewUnaryHandler(
		AuthServiceKeyBundlePutProcedure,
		svc.KeyBundlePut,
		connect.WithSchema(authServiceMethods.ByName("KeyBundlePut")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceKeyBundleGetHandler := connect.NewUnaryHandler(
		AuthServiceKeyBundleGetProcedure,
		svc.KeyBundleGet,
		connect.WithSchema(authServiceMethods.ByName("KeyBundleGet")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceKeyBundleRetryHandler := connect.NewUnaryHandler(
		AuthServiceKeyBundleRetryProcedure,
		svc.KeyBundleRetry,
		connect.WithSchema(authServiceMethods.ByName("KeyBundleRetry")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceRegisterDevicePublicKeyHandler := connect.NewUnaryHandler(
		AuthServiceRegisterDevicePublicKeyProcedure,
		svc.RegisterDevicePublicKey,
		connect.WithSchema(authServiceMethods.ByName("RegisterDevicePublicKey")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceSetDisplayNameHandler := connect.NewUnaryHandler(
		AuthServiceSetDisplayNameProcedure,
		svc.SetDisplayName,
		connect.WithSchema(authServiceMethods.ByName("SetDisplayName")),
		connect.WithHandlerOptions(opts...),
	)
	return "/cinch.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceLoginProcedure:
			authServiceLoginHandler.ServeHTTP(w, r)
		case AuthServiceDeviceCodeStartProcedure:
			authServiceDeviceCodeStartHandler.ServeHTTP(w, r)
		case AuthServiceDeviceCodePollProcedure:
			authServiceDeviceCodePollHandler.ServeHTTP(w, r)
		case AuthServiceDeviceCodeCompleteProcedure:
			authServiceDeviceCodeCompleteHandler.ServeHTTP(w, r)
		case AuthServiceDeviceCodeDenyProcedure:
			authServiceDeviceCodeDenyHandler.ServeHTTP(w, r)
		case AuthServiceRevokeDeviceProcedure:
			authServiceRevokeDeviceHandler.ServeHTTP(w, r)
		case AuthServiceKeyBundlePutProcedure:
			authServiceKeyBundlePutHandler.ServeHTTP(w, r)
		case AuthServiceKeyBundleGetProcedure:
			authServiceKeyBundleGetHandler.ServeHTTP(w, r)
		case AuthServiceKeyBundleRetryProcedure:
			authServiceKeyBundleRetryHandler.ServeHTTP(w, r)
		case AuthServiceRegisterDevicePublicKeyProcedure:
			authServiceRegisterDevicePublicKeyHandler.ServeHTTP(w, r)
		case AuthServiceSetDisplayNameProcedure:
			authServiceSetDisplayNameHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) Login(context.Context, *connect.Request[cinchv1.LoginRequest]) (*connect.Response[cinchv1.LoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cinch.v1.AuthService.Login is not implemented"))
}

func (UnimplementedAuthServiceHandler) DeviceCodeStart(context.Context, *connect.Request[cinchv1.DeviceCodeStartRequest]) (*connect.Response[cinchv1.DeviceCodeStartResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cinch.v1.AuthService.DeviceCodeStart is not implemented"))
}

func (UnimplementedAuthServiceHandler) DeviceCodePoll(context.Context, *connect.Request[cinchv1.DeviceCodePollRequest]) (*connect.Response[cinchv1.DeviceCodePollResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cinch.v1.AuthService.DeviceCodePoll is not implemented"))
}

func (UnimplementedAuthServiceHandler) DeviceCodeComplete(context.Context, *connect.Request[cinchv1.DeviceCodeCompleteRequest]) (*connect.Response[cinchv1.DeviceCodeCompleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cinch.v1.AuthService.DeviceCodeComplete is not implemented"))
}

func (UnimplementedAuthServiceHandler) DeviceCodeDeny(context.Context, *connect.Request[cinchv1.DeviceCodeDenyRequest]) (*connect.Response[cinchv1.DeviceCodeDenyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cinch.v1.AuthService.DeviceCodeDeny is not implemented"))
}

func (UnimplementedAuthServiceHandler) RevokeDevice(context.Context, *connect.Request[cinchv1.RevokeDeviceRequest]) (*connect.Response[cinchv1.RevokeDeviceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cinch.v1.AuthService.RevokeDevice is not implemented"))
}

func (UnimplementedAuthServiceHandler) KeyBundlePut(context.Context, *connect.Request[cinchv1.KeyBundlePutRequest]) (*connect.Response[cinchv1.KeyBundlePutResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cinch.v1.AuthService.KeyBundlePut is not implemented"))
}

func (UnimplementedAuthServiceHandler) KeyBundleGet(context.Context, *connect.Request[cinchv1.KeyBundleGetRequest]) (*connect.Response[cinchv1.KeyBundleGetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cinch.v1.AuthService.KeyBundleGet is not implemented"))
}

func (UnimplementedAuthServiceHandler) KeyBundleRetry(context.Context, *connect.Request[cinchv1.KeyBundleRetryRequest]) (*connect.Response[cinchv1.KeyBundleRetryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cinch.v1.AuthService.KeyBundleRetry is not implemented"))
}

func (UnimplementedAuthServiceHandler) RegisterDevicePublicKey(context.Context, *connect.Request[cinchv1.RegisterDevicePublicKeyRequest]) (*connect.Response[cinchv1.RegisterDevicePublicKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cinch.v1.AuthService.RegisterDevicePublicKey is not implemented"))
}

func (UnimplementedAuthServiceHandler) SetDisplayName(context.Context, *connect.Request[cinchv1.SetDisplayNameRequest]) (*connect.Response[cinchv1.SetDisplayNameResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cinch.v1.AuthService.SetDisplayName is not implemented"))
}
