// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: cinch/v1/event_stream.proto

package cinchv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	cinchv1 "github.com/cinchcli/relay/internal/cinchv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EventStreamServiceName is the fully-qualified name of the EventStreamService service.
	EventStreamServiceName = "cinch.v1.EventStreamService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EventStreamServiceSubscribeProcedure is the fully-qualified name of the EventStreamService's
	// Subscribe RPC.
	EventStreamServiceSubscribeProcedure = "/cinch.v1.EventStreamService/Subscribe"
)

// EventStreamServiceClient is a client for the cinch.v1.EventStreamService service.
type EventStreamServiceClient interface {
	// Subscribe opens a server-streaming channel that delivers events to the desktop agent.
	// The caller authenticates via Authorization: Bearer <per-device-token>.
	Subscribe(context.Context, *connect.Request[cinchv1.SubscribeRequest]) (*connect.ServerStreamForClient[cinchv1.ServerEvent], error)
}

// NewEventStreamServiceClient constructs a client for the cinch.v1.EventStreamService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEventStreamServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EventStreamServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	eventStreamServiceMethods := cinchv1.File_cinch_v1_event_stream_proto.Services().ByName("EventStreamService").Methods()
	return &eventStreamServiceClient{
		subscribe: connect.NewClient[cinchv1.SubscribeRequest, cinchv1.ServerEvent](
			httpClient,
			baseURL+EventStreamServiceSubscribeProcedure,
			connect.WithSchema(eventStreamServiceMethods.ByName("Subscribe")),
			connect.WithClientOptions(opts...),
		),
	}
}

// eventStreamServiceClient implements EventStreamServiceClient.
type eventStreamServiceClient struct {
	subscribe *connect.Client[cinchv1.SubscribeRequest, cinchv1.ServerEvent]
}

// Subscribe calls cinch.v1.EventStreamService.Subscribe.
func (c *eventStreamServiceClient) Subscribe(ctx context.Context, req *connect.Request[cinchv1.SubscribeRequest]) (*connect.ServerStreamForClient[cinchv1.ServerEvent], error) {
	return c.subscribe.CallServerStream(ctx, req)
}

// EventStreamServiceHandler is an implementation of the cinch.v1.EventStreamService service.
type EventStreamServiceHandler interface {
	// Subscribe opens a server-streaming channel that delivers events to the desktop agent.
	// The caller authenticates via Authorization: Bearer <per-device-token>.
	Subscribe(context.Context, *connect.Request[cinchv1.SubscribeRequest], *connect.ServerStream[cinchv1.ServerEvent]) error
}

// NewEventStreamServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEventStreamServiceHandler(svc EventStreamServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	eventStreamServiceMethods := cinchv1.File_cinch_v1_event_stream_proto.Services().ByName("EventStreamService").Methods()
	eventStreamServiceSubscribeHandler := connect.NewServerStreamHandler(
		EventStreamServiceSubscribeProcedure,
		svc.Subscribe,
		connect.WithSchema(eventStreamServiceMethods.ByName("Subscribe")),
		connect.WithHandlerOptions(opts...),
	)
	return "/cinch.v1.EventStreamService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EventStreamServiceSubscribeProcedure:
			eventStreamServiceSubscribeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEventStreamServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEventStreamServiceHandler struct{}

func (UnimplementedEventStreamServiceHandler) Subscribe(context.Context, *connect.Request[cinchv1.SubscribeRequest], *connect.ServerStream[cinchv1.ServerEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("cinch.v1.EventStreamService.Subscribe is not implemented"))
}
