// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: cinch/v1/me.proto

package cinchv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	cinchv1 "github.com/cinchcli/relay/internal/cinchv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MeServiceName is the fully-qualified name of the MeService service.
	MeServiceName = "cinch.v1.MeService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MeServiceGetMeProcedure is the fully-qualified name of the MeService's GetMe RPC.
	MeServiceGetMeProcedure = "/cinch.v1.MeService/GetMe"
)

// MeServiceClient is a client for the cinch.v1.MeService service.
type MeServiceClient interface {
	// GetMe returns the caller's plan + usage. Auth required.
	// Mirrors GET /v1/me (no REST passthrough yet — Connect-only).
	GetMe(context.Context, *connect.Request[cinchv1.GetMeRequest]) (*connect.Response[cinchv1.GetMeResponse], error)
}

// NewMeServiceClient constructs a client for the cinch.v1.MeService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMeServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MeServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	meServiceMethods := cinchv1.File_cinch_v1_me_proto.Services().ByName("MeService").Methods()
	return &meServiceClient{
		getMe: connect.NewClient[cinchv1.GetMeRequest, cinchv1.GetMeResponse](
			httpClient,
			baseURL+MeServiceGetMeProcedure,
			connect.WithSchema(meServiceMethods.ByName("GetMe")),
			connect.WithClientOptions(opts...),
		),
	}
}

// meServiceClient implements MeServiceClient.
type meServiceClient struct {
	getMe *connect.Client[cinchv1.GetMeRequest, cinchv1.GetMeResponse]
}

// GetMe calls cinch.v1.MeService.GetMe.
func (c *meServiceClient) GetMe(ctx context.Context, req *connect.Request[cinchv1.GetMeRequest]) (*connect.Response[cinchv1.GetMeResponse], error) {
	return c.getMe.CallUnary(ctx, req)
}

// MeServiceHandler is an implementation of the cinch.v1.MeService service.
type MeServiceHandler interface {
	// GetMe returns the caller's plan + usage. Auth required.
	// Mirrors GET /v1/me (no REST passthrough yet — Connect-only).
	GetMe(context.Context, *connect.Request[cinchv1.GetMeRequest]) (*connect.Response[cinchv1.GetMeResponse], error)
}

// NewMeServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMeServiceHandler(svc MeServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	meServiceMethods := cinchv1.File_cinch_v1_me_proto.Services().ByName("MeService").Methods()
	meServiceGetMeHandler := connect.NewUnaryHandler(
		MeServiceGetMeProcedure,
		svc.GetMe,
		connect.WithSchema(meServiceMethods.ByName("GetMe")),
		connect.WithHandlerOptions(opts...),
	)
	return "/cinch.v1.MeService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MeServiceGetMeProcedure:
			meServiceGetMeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMeServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMeServiceHandler struct{}

func (UnimplementedMeServiceHandler) GetMe(context.Context, *connect.Request[cinchv1.GetMeRequest]) (*connect.Response[cinchv1.GetMeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cinch.v1.MeService.GetMe is not implemented"))
}
